### ISSUE TITLE
Enable C# 8 Nullable Reference Types

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Framework#127]
### Describe the feature

Add [C# 8 Nullable Reference Types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references).

**Comment by VictorioBerra** [comment]
Please make this an optional flag to enable.

**Comment by RehanSaeed** [comment]
Well, this is in the framework project. So no flags here, so closing this.

In the templates, I think having an optional feature will be very difficult. It will mean a huge number of `#if FOO` directives. Not sure. Need to play with it to see.

**Comment by VictorioBerra** [comment]
The big thing is that it changes the entire way someone programs. Its almost like writing a whole new language. Only a small fraction of people are using it every day.

**Comment by RehanSaeed** [comment]
Fixed by https://github.com/Dotnet-Boxed/Framework/pull/276
