### ISSUE TITLE
Make "name" in DotnetNewAsync optional

### ISSUE THREAD

**Issue by neoaisac** [Dotnet-Boxed/Framework#176]
### Make "name" in DotnetNewAsync extension method optional

On `Boxed.DotnetNewTest.TempDirectoryExtensions` make argument `name` optional or nullable, to be able to test scenarios where `preferNameDirectory` is set to `true`.

At the moment, `name` is a required field that cannot be set to `null`. The default behavior of `dotnet new` when the `--name` parameter is passed is to create a subfolder at the root with the given name, and then incorporate the contents of the template. However, in when `--name` is not passed, the folder is not created and the root's name is taken as `--name` by default.

This last scenario cannot be tested with the current tooling.

**Comment by RehanSaeed** [comment]
Fixed and released soon.
