### ISSUE TITLE
Where is the documentation for Dotnet-Boxed?

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Framework#21]
I checked the GitHub and the Blog and cannot find detailed documentation anywhere. I think this is something incredibly important to have and it should be front and center in the README.md

**Comment by RehanSaeed** [comment]
Added a bunch of documentation to the ReadMe with links to blog posts. Feel free to submit a PR to add more.

**Comment by VictorioBerra** [comment]
That looks GREAT! Nice job.
