### ISSUE TITLE
Mapping Immutable Types

### ISSUE THREAD

**Issue by Frost84** [Dotnet-Boxed/Framework#237]
Hi.

Is there exists a way to map enum types? For example I have two enums A and B and want to map A to B.
```C#
public enum A
{
	A1 = 0,
	A2 = 1
}

public enum B
{
	B1 = 0,
	B2 = 1
}

internal sealed class SomeMapper : IMapper<A, B>
{
	public void Map(A source, B destination) =>
		destination = source switch
		{
			A.A1 => B.B1,
			A.A2 => B.B2,
			_ => throw new ArgumentException("Unknown enum value", nameof(source)),
		};
}

new SomeMapper(A2).Map(src); // Here is always B1 as default value for B.
```
Have I missed something or there is no way to map value types?

**Comment by RehanSaeed** [comment]
I normally use an extension method for this type of mapping. However, given that C# 9 `records` are also now a thing, I plan to introduce `IImmutableMapper<A, B>`. That would allow you to write your mapper.

```
public interface IImmutableMapper<A, B>
{
	public B Map(A source)
}
```

**Comment by Frost84** [comment]
Thanks a lot for response.

**Comment by RehanSaeed** [comment]
Fixed by https://github.com/Dotnet-Boxed/Framework/pull/238. Release will be soon.
