### ISSUE TITLE
Boxed.AspNetCore.TagHelpers.SubresourceIntegrityTagHelper v5.0.1 with asp.net core 5.0 

### ISSUE THREAD

**Issue by dotnetshadow** [Dotnet-Boxed/Framework#252]
Just opening up the issue to confirm it's still a problem with version 5.0.1 of the nuget package
#117 

More information here:
https://github.com/Dotnet-Boxed/Framework/issues/117#issuecomment-760953615

**Comment by RehanSaeed** [comment]
Feel free to reopen if you have more information.
