### ISSUE TITLE
ILoggerFactory extension methods appear mistargeted?

### ISSUE THREAD

**Issue by alexrp** [Dotnet-Boxed/Framework#293]
There is an example in the README:

```csharp
loggerfactory
    .AddIfElse(
        hostingEnvironment.IsDevelopment(),
        x => x.AddConsole(...).AddDebug(),
        x => x.AddSerilog(...));
```

I'm not sure this makes any sense. Methods like `AddConsole` and `AddDebug` are extensions on `ILoggingBuilder`, *not* `ILoggerFactory`. It seems to me like the `LoggerFactoryExtensions` type is completely mistargeted, but perhaps I'm just missing something.

**Comment by RehanSaeed** [comment]
This documentation has not kept up to date with changes in the API's. I'd take a quick PR if you want to fix it?

**Comment by VictorioBerra** [comment]
@alexrp You can do `WriteTo.Conditional`:

https://github.com/Dotnet-Boxed/Templates/blob/main/Source/ApiTemplate/Source/ApiTemplate/Program.cs#L173-L175

**Comment by alexrp** [comment]
@RehanSaeed The actual code is targeting `ILoggerFactory`, it's not just a documentation issue: https://github.com/Dotnet-Boxed/Framework/blob/main/Source/Boxed.AspNetCore/LoggerFactoryExtensions.cs

I could send a PR to retarget that API at `ILoggingBuilder`, but it would be a breaking change. I'm not sure what your policy is for that, so I decided to open an issue instead.

@VictorioBerra That's a Serilog API. I'm talking about `Microsoft.Extensions.Logging`.

**Comment by VictorioBerra** [comment]
@alexrp I wasn't sure what your use case is. 

I guess they are depreciated:

- https://github.com/dotnet/AspNetCore.Docs/issues/9829
- https://stackoverflow.com/questions/53840298/how-to-fix-obsolete-iloggerfactory-methods

So I am voting for the breaking change,  we target net5.0 anyway. But if we are against that, there's no reason we couldn't just create a new extensions file called `LoggerBuilderExtensions` and leave the old one in place.

**Comment by RehanSaeed** [comment]
@alexrp I'm with you now.

> I could send a PR to retarget that API at ILoggingBuilder, but it would be a breaking change. I'm not sure what your policy is for that, so I decided to open an issue instead.

We'd accept that PR as a breaking change. We'd also increment the major version. It shouldn't affect anyone, since it doesn't make much sense to use the old API.
