### ISSUE TITLE
[Boxed.DotnetNewTest] Add uninstall command

### ISSUE THREAD

**Issue by johanndev** [Dotnet-Boxed/Framework#357]
### Describe the feature

Hi there!

First, I wanted to say thanks for your work on these packages - they are all very useful!

I'm currently developing a ASP.NET Core project template and your Boxed.DotnetNewTest package is incredible helpful and a real time saver, compared to manually installing my template over and over again ^^

During development, I sometimes run into problems because the dotnet cli seems to use a stale version of my template; i.e., I change the available symbols in my `template.json`, but the changes are not picked up on the next run of my unit test.

Uninstalling the template between test runs reliable fixes these problems.

I therefore propose to add a new `DotnetNew.UninstallAsync` method (similar to the existing `DotnewNew.InstallAsync` method) to enable users of the library to programmatically uninstall project templates.

I already prepared the necessary changes to the library in a local branch - I would be very happy to open a PR with my changes, if you agree that it would be a useful addition to your library.

Thanks!

**Comment by RehanSaeed** [comment]
Sounds good, will be happy to accept the PR.
