### ISSUE TITLE
[TagHelpers] How to use TwitterCard?

### ISSUE THREAD

**Issue by xperiandri** [Dotnet-Boxed/Framework#394]
### Describe the bug

Please, update `TwitterCard` docs as they are not relevant.
Also, the tag in docs must be autoclosed (trailing slash). Because otherwise, it corrupts HTML if something is bad with tag helper.

### Expected behaviour

Copy-pasting from docs allows using `TwitterCard` tag helper

**Comment by RehanSaeed** [comment]
Fixed in https://github.com/Dotnet-Boxed/Framework/pull/395

If there is anything else, please feel free to raise a PR.
