### ISSUE TITLE
[Boxed.DotnetNewTest] Mismatched ports when testing ASP.NET Core templates

### ISSUE THREAD

**Issue by johanndev** [Dotnet-Boxed/Framework#408]
### Describe the bug

I'm trying to test my ASP.NET Core project template to ensure that all appropriate endpoints are available as expected. Unfortunately, the `readinessCheck` delegate in `DotnetRunAsync` never completes successfully and is cancelled after 2 min.

After stepping through the code, I observed that the automatically chosen ports are never propagated to the ASP.NET Core application. The app rather uses the automatically chosen ports (configured in `launchsettings.json`). The automatically configured HttpClients in the `readinessCheck` lambda have their baseUrls set to the ports determined by the `PortHelper.GetFreeTcpPort()` helper chosen during `DotnetNewAsync`.

Accessing the endpoint shown in the console window (enabled via `showShellWindow: true`) shows that the app was successfully started and the endpoints can be reached.

A solution could be to pass the ports determined by `PortHelper.GetFreeTcpPort()` via the `--urls` Argument to `dotnet run`.

### Steps to reproduce

1. Create a new xunit test project
2. Add the following test case:
	```csharp
    public async Task Run_DefaultArguments_IsSuccessful()
    {
    	await using var tempDirectory = TempDirectory.NewTempDirectory();
    	var project = await tempDirectory.DotnetNewAsync("webapi", "DefaultArguments");
    	await project.DotnetRestoreAsync();
    	await project.DotnetBuildAsync();
    	await project.DotnetRunAsync(
    		projectRelativeDirectoryPath: "",
    		readinessCheck: async (httpClient, httpsClient) =>
    		{
    			var httpResponse = await httpsClient.GetAsync("weatherforecast");
    			return httpResponse.IsSuccessStatusCode;
    		},
    		action: async (httpClient, httpsClient) =>
    		{
    			var httpResponse = await httpsClient.GetAsync("weatherforecast");
    			Assert.Equal(HttpStatusCode.OK, httpResponse.StatusCode);
    		},
    		showShellWindow: true);
    }
	```
3. Run the test
4. Observe that the test never completes, but is cancelled after approx. 2 min

### Expected behaviour

The basic test case can be successfully executed.

**Comment by RehanSaeed** [comment]
I've gone back and forth on this one as there are many ways to set the ports. This is what I currently do:

1. Setup port variables in your `template.json` file, so users can set a port themselves if they wish.
```json
"HttpsPort": {
      "type": "parameter",
      "datatype": "integer",
      "defaultValue": "5001",
      "displayName": "HTTPS Port",
      "description": "Port number to use for the Kestrel HTTPS endpoint in launchSettings.json."
    },
    "HttpsPortConstant": {
      "type": "generated",
      "generator": "constant",
      "parameters": {
        "value": "5001"
      }
    },
    "HttpsPortReplacer": {
      "type": "generated",
      "generator": "coalesce",
      "parameters": {
        "sourceVariableName": "HttpsPort",
        "fallbackVariableName": "HttpsPortConstant"
      },
      "replaces": "5001"
    },
```

When running `dotnet new` pass in the port:

```
var project = await tempDirectory
    .DotnetNewAsync(
        "Foo",
        "ApiDefaults",
        new Dictionary<string, string>()
        {
            { "https-port", "{HTTPS_PORT}" },
            { "http-port", "{HTTP_PORT}" },
        });
    .ConfigureAwait(false);
```

If you take a look at the `project` variable, it contains the ports used. If you then call `DotnetRunAsync` it will work. The other alternatives are to pass the ports through the `--url` parameter or via environment variables but I found these to be less reliable methods personally.
