### ISSUE TITLE
Migration guide for IAsyncCommand

### ISSUE THREAD

**Issue by rutemja** [Dotnet-Boxed/Framework#434]
### Describe the feature

Hi,

we are using the IAsyncCommand interfaces from this project, but now they have been removed during NET6 update - without notice.

Is there now a better way to get this functionality?
If yes: It would be nice to have a short migration guide.

Thank you!

**Comment by RehanSaeed** [comment]
You can take a copy of those interfaces from the older NuGet package and use those going forward in your own class library.
