### ISSUE TITLE
[Question] IAsyncMapper with EF Core 6

### ISSUE THREAD

**Issue by GiannhsR** [Dotnet-Boxed/Framework#466]
Hello,

I have faced an issue whilst using the provided [IAsyncMapper](https://www.nuget.org/packages/Boxed.Mapping/) and I was wondering if you could provide some additional information.

I have the following model:
```
public class Blog
{
  public string Id {get; set;}
  public string Name {get; set;}
}
```
and the associadted view model:
```
public class BlogViewModel
{
  public string Name {get; set;}
}
```

I create and then register the associated mapper as a Scoped Service
```
public class BlogToBlogViewModelMapper : IAsyncMapper<Blog, BlogViewModel>
{
  private readonly Blogrepository blogrepository;
  public BlogToBlogViewModelMapper (Blogrepository blogrepository)
  {
    this.blogrepository = blogrepository
  }
  
  public async Task MapAsync(Blog source, BlogViewModel destination, CancellationToken token)
  {
    destination.Name = await this.blogrepository.GetBlogName(token);
  }
}
```
`Blogrepository` is also registered as a scoped service

Now, in another class where I want to make a mapping
```
public class Example
{
  private readonly Blogrepository blogrepository;
  private IAsyncMapper<Blog, BlogViewModel> myAsyncMapper;
  public Example(
  Blogrepository blogrepository
  IAsyncMapper<Blog, BlogViewModel> myAsyncMapper)
  {
    this.blogrepository = blogrepository;
    this.myAsyncMapper = myAsyncMapper;
  }

  List<Blog> models = await this.blogrepository.GetBlogs();
  
  List<BlogViewModels> updateModels = await this.myAsyncMapper.MapListAsync(models, CancellationToken.None);
}
```
when the aforementioned `myAsyncMapper.MapListAsync(models, CancellationToken.None);` is executed, I get the following [error](https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues):

> A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe.

I am trying to figure out what is the source of the problem here.

- Are my services registered with the wrong lifetime? (Both Blogrepository and IAsyncMapper are registered as scoped)
- Should I create a `new DbContext()` each time I want to run `blogrepository.GetBlogName(token);`?

Any information or resource is appreciated

**Comment by RehanSaeed** [comment]
Perhaps this could be because `MapListAsync` is doing things in parallel. Just a guess. You can try using a foreach instead and mapping individually.

**Comment by GiannhsR** [comment]
> Perhaps this could be because `MapListAsync` is doing things in parallel. Just a guess. You can try using a foreach instead and mapping individually.

Thanks for the answer.
I will try that and reply back with the results.

**Comment by GiannhsR** [comment]
> Perhaps this could be because `MapListAsync` is doing things in parallel. Just a guess. You can try using a foreach instead and mapping individually.

It's working.
Thank you.
