### ISSUE TITLE
RequestCanceledMiddleware cannot work when url use 0.0.0.0

### ISSUE THREAD

**Issue by zxbeltm** [Dotnet-Boxed/Framework#507]
### Describe the bug

When I Set asp.net core's applicationUrl to 'http://0.0.0.0:8080', the RequestCanceledMiddleware not work.
But it is working well in 'http://127.0.0.1:8080' or 'http://localhost:8080'

![real ip](https://user-images.githubusercontent.com/103971861/187832904-9dc681dc-ba58-4d22-996d-6fce94e1183e.png)
![localhost](https://user-images.githubusercontent.com/103971861/187832867-b28d3982-2f08-4491-b105-a6a40c1de3a3.png)
![127IP](https://user-images.githubusercontent.com/103971861/187832875-89fafcd3-60a3-4565-a9af-0181f5f7c935.jpg)

### Steps to reproduce

``` launchSettings.json
"profiles": {
    "LTM.Module.CCM.TiehejiService01": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "applicationUrl": "http://0.0.0.0:5074",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
```
```Program.cs
app.UseHttpException();
app.UseRequestCanceled();
```

### Expected behaviour

none

**Comment by RehanSaeed** [comment]
The middleware (code below) doesn't do anything with the host part of the URL. It only looks for `OperationCanceledException` and `HttpContext.RequestAborted.IsCancellationRequested`.

https://github.com/Dotnet-Boxed/Framework/blob/main/Source/Boxed.AspNetCore/Middleware/RequestCanceledMiddleware.cs

**Comment by zxbeltm** [comment]
> The middleware (code below) doesn't do anything with the host part of the URL. It only looks for `OperationCanceledException` and `HttpContext.RequestAborted.IsCancellationRequested`.
> 
> https://github.com/Dotnet-Boxed/Framework/blob/main/Source/Boxed.AspNetCore/Middleware/RequestCanceledMiddleware.cs

Thanks.By the way,do you know why ```token.ThrowIfCancellationRequested();``` can not  throw exception when i changed the url to "http://0.0.0.0:5074" and cancel the request in edge?

**Comment by RehanSaeed** [comment]
Sorry, I'm not sure. What error do you get? That might be a question to ask in the ASP.NET repo.
