### ISSUE TITLE
Add support for the new new Core 2.2 options validation in ConfigureSingleton.

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Framework#62]
- https://github.com/aspnet/Options/pull/266
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#options-validation

Somehow we would have to expose the options builder. Or add a new method.

﻿**Which project template is the issue about?**
Framework

**Which version of the project template is the issue about?**
Latest

**Which version of Visual Studio or the dotnet SDK were you using?**
2.2

**Comment by RehanSaeed** [comment]
Added `ConfigureAndValidateSingleton` extension method to `IServiceCollection`.
