### ISSUE TITLE
Release Boxed.DotNetNew to NuGet

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Framework#92]
Thanks for merging!

**Comment by RehanSaeed** [comment]
https://github.com/Dotnet-Boxed/Framework/releases/tag/Boxed.DotnetNewTest.1.0.0

**Comment by VictorioBerra** [comment]
@RehanSaeed https://www.nuget.org/packages?q=Boxed.DotnetNewTest

## 0 packages returned for Boxed.DotnetNewTest

??

**Comment by RehanSaeed** [comment]
Yes, there was a build failure:

https://dev.azure.com/dotnet-boxed/Framework/_build/results?buildId=100&view=logs&s=d4a9a205-d52e-57fb-7b17-15a9d984af62&j=5e9c7db0-5201-5dbb-4059-f41d70fa56e6

Still trying to get to grips with Azure Pipelines Nuget push task. Seems like I'm missing something with it.
